spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SportPerformance
    username: ENC(0PejicAkhlkzs0RVyEUZtQ==)
    password: ENC(0PejicAkhlkzs0RVyEUZtQ==)
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
